ServerName localhost
User www-data
Group www-data

# Add Python path globally (outside VirtualHost)
WSGIPythonPath /app

Include ports.conf
LoadModule mpm_prefork_module /usr/lib/apache2/modules/mod_mpm_prefork.so
IncludeOptional mods-enabled/*.load
IncludeOptional mods-enabled/*.conf
IncludeOptional sites-enabled/*.conf
ErrorLog ${APACHE_LOG_DIR}/error.log
LogLevel warn