services:
  medisafe:
    build:
      context: .
      dockerfile: docker/DockerFile
    container_name: medisafe-app

    ports:
      - "80:80"
      - "443:443"

    volumes:
      - .:/app

      - ./staticfiles:/app/staticfiles
      - ./mediafiles:/app/mediafiles

    environment:
      - DJANGO_SETTINGS_MODULE=capstone.settings
    env_file:
      - .env

    restart: unless-stopped
