# Generated by Django 6.0 on 2026-07-14 05:23

import MediSafe.helpers
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub')], help_text='OAuth provider name', max_length=50)),
                ('provider_user_id', models.CharField(help_text='User ID from the OAuth Provider', max_length=255)),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token (if available)', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Token expiration timestamp', null=True)),
                ('provider_name', models.CharField(help_text='Full name from OAuth Provider', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the OAuth account was linked')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Late updated at ')),
            ],
        ),
        migrations.CreateModel(
            name='UserMedications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage_amount_mg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dosage_frequency', models.CharField(default='unknown', max_length=100)),
                ('last_refill', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.CharField(default='UnIdentified', max_length=100)),
                ('medication_more', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique Identifier for the user', primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="User's Full Name", max_length=255)),
                ('pass_hash', models.CharField(blank=True, help_text='hashed password for user', max_length=255, null=True)),
                ('email', models.EmailField(blank=True, error_messages={'unique': 'A user with this email already exists.'}, help_text="User's email", max_length=255, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the account was created')),
                ('last_logged_in_at', models.DateTimeField(blank=True, help_text="Timestamp of user's last login", null=True)),
                ('is_oauth_user', models.BooleanField(default=False, help_text='Does user use OAuth for authentication?')),
            ],
        ),
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_bank_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('common_name', models.CharField(unique=True)),
                ('synonyms', models.CharField()),
                ('smile_structure', models.CharField()),
            ],
            options={
                'indexes': [models.Index(django.db.models.functions.text.Lower('common_name'), name='drug_common_name_lower_idx')],
            },
        ),
        migrations.CreateModel(
            name='Drug_Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.TextField(max_length=20)),
                ('severity_level', models.IntegerField()),
                ('first_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_drug', to='MediSafe.drug')),
                ('second_drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_drug', to='MediSafe.drug')),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('interaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction', to='MediSafe.drug_interactions')),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='MediSafe.users')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=MediSafe.helpers.get_profile_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('two_factor_auth', models.BooleanField(default=False, help_text='2FA, enabled? ')),
                ('safety_alerts', models.BooleanField(default=False, help_text="User's noti pred for high-priority safety alerts")),
                ('monthly_usage_reports', models.BooleanField(default=False, help_text='Noti Pref for monthly logs, probably mailed')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['email'], name='MediSafe_us_email_e4962d_idx'),
        ),
        migrations.AddField(
            model_name='usermedications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersMedications', to='MediSafe.users'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='MediSafe.users'),
        ),
        migrations.AddField(
            model_name='oauthaccount',
            name='user',
            field=models.ForeignKey(help_text='Reference to main user account', on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accounts', to='MediSafe.users'),
        ),
        migrations.AddIndex(
            model_name='drug_interactions',
            index=models.Index(fields=['first_drug', 'second_drug'], name='MediSafe_dr_first_d_f0e893_idx'),
        ),
        migrations.AddIndex(
            model_name='usermedications',
            index=models.Index(fields=['user', 'last_refill'], name='MediSafe_us_user_id_811a81_idx'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['user', '-date_time'], name='MediSafe_us_user_id_52cba7_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(fields=['provider', 'provider_user_id'], name='MediSafe_oa_provide_bc6aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(fields=['user', 'provider'], name='MediSafe_oa_user_id_ae230b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='oauthaccount',
            unique_together={('provider', 'provider_user_id')},
        ),
    ]
