# Generated by Django 6.0 on 2026-03-21 13:44

import MediSafe.helpers
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique Identifier for the user', primary_key=True, serialize=False)),
                ('full_name', models.CharField(help_text="User's Full Name", max_length=255)),
                ('pass_hash', models.CharField(help_text='hashed password for user', max_length=255)),
                ('email', models.EmailField(error_messages={'blank': 'Email field cannot be empty', 'null': 'Email field cannot be null', 'unique': 'A user with this email already exists.'}, help_text="User's email", max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the account was created')),
                ('last_logged_in_at', models.DateTimeField(blank=True, help_text="Timestamp of user's last login", null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to='MediSafe.users')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=MediSafe.helpers.get_profile_upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'user_profiles',
            },
        ),
        migrations.AddIndex(
            model_name='users',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
    ]
