# Generated by Django 6.0 on 2026-07-15 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediSafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('otp', models.TextField(max_length=5)),
                ('expiration_time', models.DateTimeField()),
                ('attempts', models.IntegerField(default=0)),
            ],
        ),
    ]
