# Generated by Django 6.0 on 2026-04-17 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediSafe', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMedications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage_amount_mg', models.DecimalField(decimal_places=2, max_digits=8)),
                ('dosage_frequency', models.CharField(max_length=100)),
                ('last_refill', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.CharField(default='UnIdentified', max_length=100)),
            ],
        ),
        migrations.RenameIndex(
            model_name='users',
            new_name='MediSafe_us_email_e4962d_idx',
            old_name='users_email_4b85f2_idx',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='monthly_usage_reports',
            field=models.BooleanField(default=False, help_text='Noti Pref for monthly logs, probably mailed'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='safety_alerts',
            field=models.BooleanField(default=False, help_text="User's noti pred for high-priority safety alerts"),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='two_factor_auth',
            field=models.BooleanField(default=False, help_text='2FA, enabled? '),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table=None,
        ),
        migrations.AlterModelTable(
            name='users',
            table=None,
        ),
        migrations.AddField(
            model_name='usermedications',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usersMedications', to='MediSafe.users'),
        ),
        migrations.AddIndex(
            model_name='usermedications',
            index=models.Index(fields=['last_refill'], name='MediSafe_us_last_re_d9364d_idx'),
        ),
    ]
