# Generated by Django 6.0 on 2026-07-16 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediSafe', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug_interactions',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
