# Generated by Django 6.0 on 2026-04-18 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediSafe', '0002_usermedications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermedications',
            name='medication_more',
            field=models.TextField(blank=True, default=''),
        ),
    ]
