# Generated by Django 6.0 on 2026-06-14 05:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediSafe', '0003_usermedications_medication_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('smile_structure', models.CharField(max_length=100)),
                ('drug_bank_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('drug_synonym', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drug_Interactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('mechanism', models.TextField()),
                ('recommendation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OAuthAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('google', 'Google'), ('github', 'GitHub')], help_text='OAuth provider name', max_length=50)),
                ('provider_user_id', models.CharField(help_text='User ID from the OAuth Provider', max_length=255)),
                ('access_token', models.TextField(help_text='OAuth access token')),
                ('refresh_token', models.TextField(blank=True, help_text='OAuth refresh token (if available)', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, help_text='Token expiration timestamp', null=True)),
                ('provider_name', models.CharField(help_text='Full name from OAuth Provider', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When the OAuth account was linked')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Late updated at ')),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=20, unique=True)),
                ('info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='users',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='usermedications',
            name='MediSafe_us_last_re_d9364d_idx',
        ),
        migrations.AddField(
            model_name='users',
            name='is_oauth_user',
            field=models.BooleanField(default=False, help_text='Does user use OAuth for authentication?'),
        ),
        migrations.AlterField(
            model_name='usermedications',
            name='dosage_frequency',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='Unique Identifier for the user', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='pass_hash',
            field=models.CharField(blank=True, help_text='hashed password for user', max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='usermedications',
            index=models.Index(fields=['user', 'last_refill'], name='MediSafe_us_user_id_811a81_idx'),
        ),
        migrations.AddField(
            model_name='drug_interactions',
            name='first_drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_drug', to='MediSafe.drug'),
        ),
        migrations.AddField(
            model_name='drug_interactions',
            name='second_drug',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_drug', to='MediSafe.drug'),
        ),
        migrations.AddField(
            model_name='oauthaccount',
            name='user',
            field=models.ForeignKey(help_text='Reference to main user account', on_delete=django.db.models.deletion.CASCADE, related_name='oauth_accounts', to='MediSafe.users'),
        ),
        migrations.AddField(
            model_name='drug_interactions',
            name='severity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MediSafe.severity'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='interaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction', to='MediSafe.drug_interactions'),
        ),
        migrations.AddField(
            model_name='userhistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='MediSafe.users'),
        ),
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(fields=['provider', 'provider_user_id'], name='MediSafe_oa_provide_bc6aa3_idx'),
        ),
        migrations.AddIndex(
            model_name='oauthaccount',
            index=models.Index(fields=['user', 'provider'], name='MediSafe_oa_user_id_ae230b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='oauthaccount',
            unique_together={('provider', 'provider_user_id')},
        ),
        migrations.AddIndex(
            model_name='drug_interactions',
            index=models.Index(fields=['first_drug', 'second_drug'], name='MediSafe_dr_first_d_f0e893_idx'),
        ),
        migrations.AddIndex(
            model_name='userhistory',
            index=models.Index(fields=['user', '-date_time'], name='MediSafe_us_user_id_52cba7_idx'),
        ),
    ]
