# Generated by Django 6.0 on 2026-07-16 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediSafe', '0003_alter_drug_interactions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drug_interactions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
