# Generated by Django 6.0 on 2026-06-14 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediSafe', '0004_drug_drug_interactions_oauthaccount_severity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, error_messages={'blank': 'Email field cannot be empty', 'null': 'Email field cannot be null', 'unique': 'A user with this email already exists.'}, help_text="User's email", max_length=255, null=True, unique=True),
        ),
    ]
