# Generated by Django 6.0 on 2026-07-16 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediSafe', '0005_notificationtrigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtrigger',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='MediSafe.users'),
        ),
    ]
