# Generated by Django 6.0 on 2026-06-14 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediSafe', '0005_alter_users_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with this email already exists.'}, help_text="User's email", max_length=255, null=True, unique=True),
        ),
    ]
